name: exercise1

on: push

jobs:
    job1:
            runs-on: ubuntu-latest
            steps:
                    - name: date ubuntu
                      run: date
    job2:
            runs-on: windows-latest
            steps:
                    - name: date windows
                      run: date.exe +"%Y-%m-%d"
    job3:
            runs-on: macos-latest
            steps:
                    - name: date macos
                      run: date +%F
    job4:
            needs: [job1, job2, job3]
            runs-on: ubuntu-18.04
            steps:
                    - name: date ubuntu2
                      run: date
